# Generated by Django 5.1 on 2024-11-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_client_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
