# Generated by Django 5.1.2 on 2024-11-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('app', 'App'), ('Product', 'product'), ('Branding', 'branding')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
