# Generated by Django 5.1.2 on 2024-11-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_portfolioitem_client_portfolioitem_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='client',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='second_cat',
            field=models.CharField(max_length=50),
        ),
    ]
