# Generated by Django 5.1.2 on 2024-11-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_portfolioitem_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
