# Generated by Django 5.1.2 on 2024-11-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_portfolioitem_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='created',
        ),
    ]
