# Generated by Django 5.1.2 on 2024-11-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_remove_portfolioitem_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='client',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='second_cat',
        ),
    ]
