# Generated by Django 5.1.2 on 2024-11-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_remove_portfolioitem_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='descriptiom',
            new_name='description',             
        ),
    ]